#pragma config(Motor,  port2,           mom,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1==1)
	{
		if(vexRT(Btn5U)==1)
		{
			motor(port2)=127;
			motor(port3)=-127;
		}
		else if(vexRT(Btn5D)==1)
		{
			motor(port2)=-127;
			motor(port3)=127;
		}
		else
		{
			motor(port2)=0;
			motor(port3)=0;
		}

	}
motor(mom)=127;
wait(10);
motor(mom)=0;

}
